#!php
<?php declare(strict_types = 1);

define('PROJECT_ROOT', __DIR__ . '/../..');
define('PATH_PREFIX', DIRECTORY_SEPARATOR);

require PROJECT_ROOT . '/vendor/autoload.php';

use GitHook\Hook\SprykerPreCommit;

$console = new SprykerPreCommit();
$console->run();
