#!/usr/bin/php
<?php

define('PROJECT_ROOT', '/data/shop/development/current');
define('PATH_PREFIX', DIRECTORY_SEPARATOR . 'vendor/spryker/spryker/');

require PROJECT_ROOT . '/vendor/autoload.php';

use GithubHook\Hook\SprykerPreCommit;

$console = new SprykerPreCommit();
$console->run();
