language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.3
      env: PREFER_LOWEST=1

    - php: 7.4
      env: CHECKS=1 DEFAULT=0

  fast_finish: true

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

script:
  - if [[ $CHECKS == 1 ]] ; then vendor/bin/phpstan analyse -l 5 -c phpstan.neon src/ ; fi
  - if [[ $CHECKS == 1 ]] ; then composer cs-check ; fi

notifications:
  email: false

after_success:
  - travis_retry php vendor/bin/coveralls
