#!/usr/bin/php
<?php

define('PROJECT_ROOT', '/data/shop/development/current');
define('PATH_PREFIX', DIRECTORY_SEPARATOR);

require PROJECT_ROOT . '/vendor/autoload.php';

use GitHubHook\Hook\SprykerPreCommit;

$console = new SprykerPreCommit();
$console->run();
