name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, bcmath
          coverage: none

      - name: Composer Install
        run: composer install --prefer-dist --no-interaction --profile

      - name: PHPStan checks
        run: composer stan

      - name: CodeStyle checks
        run: composer cs-check

  lowest:
    name: Prefer Lowest
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, bcmath
          coverage: none

      - name: Composer Install
        run: composer install --prefer-dist --no-interaction --profile

      - name: Composer Update
        run: composer update --prefer-lowest --prefer-dist --no-interaction --profile -vvv

      - name: PHPStan checks
        run: composer stan
